language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - echo "Using SITE_PKG_DIR: $SITE_PKG_DIR"
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get install gfortran g++
  - sudo apt-get install libhdf5-serial-dev hdf5-tools
  - sudo apt-get install python-dev python-pip
  - sudo apt-get install libatlas-base-dev liblapack-dev
  - sudo apt-get install python-numpy
  - sudo apt-get install python-scipy
install: 
  - pip install matplotlib
  - pip install nose cython numexpr
  - pip install -e git+https://github.com/pydata/pandas#egg=pandas
  - pip install -r requirements.txt --use-mirrors
  - python setup.py build_ext install
# command to run tests
script: nosetests
