language: python

matrix:
  include: 
    - python: "2.7"
      env: DEPS="numpy=1.7.1 scipy=0.13.0 nose matplotlib=1.3 pandas=0.13.0 scikit-image=0.9 pyyaml pytables"
    - python: "2.7"
      env: DEPS="numpy=1.7.1 scipy=0.13.0 nose matplotlib=1.3 pandas=0.13.0 scikit-image=0.9 pyyaml numba=0.11 pytables"
    - python: "2.7"
      env: DEPS="numpy=1.8 scipy nose matplotlib=1.3 pandas=0.13.0 scikit-image=0.10.1 pyyaml numba=0.12 pytables"
    - python: "2.7"
      env: DEPS="numpy=1.8 scipy=0.14.0 nose matplotlib=1.3 pandas=0.13.0 scikit-image=0.10.1 pyyaml numba=0.12.2 pytables"
    - python: "3.4"
      env: DEPS="numpy=1.8 scipy=0.14.0 nose matplotlib=1.3 pandas=0.14.0 scikit-image=0.10.1 pyyaml pytables"

install:
  - conda install --yes -c conda conda-env
  - conda create -n testenv --yes $DEPS pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - python setup.py install

before_install:
  - sudo apt-get install libhdf5-serial-dev hdf5-tools
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # See:
  # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
  - conda update --yes --no-deps conda
  # Learned the hard way: miniconda is not always up-to-date with conda.
  - conda update --yes conda

script: nosetests --nologcapture -a '!slow'
