language: python
sudo: false

matrix:
  include:
    # "Legacy" environments: oldest supported versions, without and with numba
    - python: "2.7"
      env: DEPS="numpy=1.8.2 scipy=0.12.0 matplotlib=1.3 pillow==2.1 pandas=0.13.0 scikit-image=0.9 pyyaml pytables" BUILD_DOCS=false
    - python: "2.7"
      env: DEPS="numpy=1.8.2 scipy=0.13.3 matplotlib=1.3 pillow==2.5.1 pandas=0.13.0 scikit-image=0.9 pyyaml numba=0.13.4 pytables" BUILD_DOCS=false
    # "Recommended" environments: More recent versions, for Py2 and Py3.
    - python: "2.7"
      env: DEPS="libgfortran=1.0 numpy=1.9 scipy=0.16 matplotlib=1.4 pillow==2.9 pandas=0.16 scikit-image=0.11 pyyaml numba=0.20 pytables pyfftw" BUILD_DOCS=false
    - python: "3.4"
      env: DEPS="libgfortran=1.0 numpy=1.9 scipy=0.16 matplotlib=1.4 pillow==3.0 pandas=0.16 scikit-image=0.11 pyyaml numba=0.20 pytables pyfftw" BUILD_DOCS=true
    - python: "3.5"
      env: DEPS="numpy scipy matplotlib pillow pandas!=0.18.0 scikit-image pyyaml pytables numba"  BUILD_DOCS=false
    - python: "3.6"
      env: DEPS="numpy scipy matplotlib pillow pandas!=0.18.0 scikit-image pyyaml pytables numba"  BUILD_DOCS=false


install:
  # See:
  # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
  # - conda update --yes --no-deps conda
  # OK, this used to *fix* the build, but now it *breaks* the build.
  # If you're reading this, good luck out there. I'm not sure what to tell you.
  - conda update --yes conda
  # Append the conda-forge channel, instead of adding it. See:
  # https://github.com/conda-forge/conda-forge.github.io/issues/232)
  - conda config --append channels conda-forge
  - conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - |
      if [ $BUILD_DOCS == true ]; then
        conda install -n testenv --yes ipython=5.1.0 sphinx=1.4.8 numpydoc=0.6.0 nbconvert=4.2.0
        pip install sphinx_bootstrap_theme==0.4.12
      fi
  # for debugging...
  - echo $PATH
  - which python
  - conda info
  - conda list
  - python setup.py install

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script:
  - nosetests --nologcapture -a '!slow'
  - |
    if [ $BUILD_DOCS == true ]; then
      cd $TRAVIS_BUILD_DIR/..
      git clone https://github.com/soft-matter/trackpy-examples.git
      cd trackpy/doc
      # this expects the notebooks to be in ../../../trackpy-examples/notebooks/
      make notebooks
      make html
    fi


after_success:
    - |
      if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'soft-matter/trackpy' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then
        echo "Uploading documentation"
        cd $TRAVIS_BUILD_DIR
        openssl aes-256-cbc -K $encrypted_23ba5de49536_key -iv $encrypted_23ba5de49536_iv -in soft-matter-docs-deploy.enc -out soft-matter-docs-deploy -d
        eval `ssh-agent -s`
        chmod 600 soft-matter-docs-deploy
        ssh-add soft-matter-docs-deploy
        git config --global user.email "Travis@nomail"
        git config --global user.name "Travis"
        git config --global push.default simple
        cd ..
        git clone git@github.com:soft-matter/soft-matter.github.io.git ./doc-repo
        cd doc-repo/trackpy
        git checkout --orphan temp_branch
        git rm -rf ./dev
        mv $TRAVIS_BUILD_DIR/doc/_build/html ./dev
        if [ -n "$TRAVIS_TAG" ]; then
          cp -R dev $TRAVIS_TAG;
        fi
        git add -A
        git commit -m "Docs build of trackpy commit $TRAVIS_COMMIT"
        git branch -D master
        git branch -m master
        git push --set-upstream origin master --force
      fi
