language: python
sudo: false

matrix:
  include:
    # "Legacy" environments: oldest supported versions, without and with numba
    - python: "2.7"
      env: DEPS="numpy=1.8.2 scipy=0.12.0 matplotlib=1.3 pillow<3 pandas=0.12.0 scikit-image=0.9 pyyaml pytables pyfftw"
    - python: "2.7"
      env: DEPS="numpy=1.8.2 scipy=0.13.3 matplotlib=1.3 pillow<3 pandas=0.13.0 scikit-image=0.9 pyyaml numba=0.13.4 pytables pyfftw"
    # "Recommended" environments: More recent versions, for Py2 and Py3.
    - python: "2.7"
      env: DEPS="numpy=1.9 scipy=0.16 matplotlib=1.4 pillow<3 pandas=0.16 scikit-image=0.11 pyyaml numba=0.20 pytables pyfftw"
    - python: "3.4"
      env: DEPS="numpy=1.9 scipy=0.16 matplotlib=1.4 pillow<3 pandas=0.16 scikit-image=0.11 pyyaml numba=0.20 pytables pyfftw"
    - python: "3.5"
      env: DEPS="numpy scipy matplotlib pillow<3 pandas scikit-image pyyaml pytables numba"

install:
  # See:
  # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
  # - conda update --yes --no-deps conda
  # OK, this used to *fix* the build, but now it *breaks* the build.
  # If you're reading this, good luck out there. I'm not sure what to tell you.
  - conda update --yes conda
  - conda config --add channels soft-matter
  - conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # for debugging...
  - echo $PATH
  - which python
  - conda info
  - conda list
  - python setup.py install

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script: nosetests --nologcapture -a '!slow'
